//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRMOntology.DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class AnnotationBase
    {
        public System.Guid AnnotationId { get; set; }
        public Nullable<int> ObjectTypeCode { get; set; }
        public Nullable<System.Guid> ObjectId { get; set; }
        public Nullable<System.Guid> OwningBusinessUnit { get; set; }
        public string Subject { get; set; }
        public bool IsDocument { get; set; }
        public string NoteText { get; set; }
        public string MimeType { get; set; }
        public string LangId { get; set; }
        public string DocumentBody { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<int> FileSize { get; set; }
        public string FileName { get; set; }
        public Nullable<System.Guid> CreatedBy { get; set; }
        public Nullable<bool> IsPrivate { get; set; }
        public Nullable<System.Guid> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public byte[] VersionNumber { get; set; }
        public string StepId { get; set; }
        public Nullable<System.DateTime> OverriddenCreatedOn { get; set; }
        public Nullable<int> ImportSequenceNumber { get; set; }
        public Nullable<System.Guid> CreatedOnBehalfBy { get; set; }
        public System.Guid OwnerId { get; set; }
        public Nullable<System.Guid> ModifiedOnBehalfBy { get; set; }
        public int OwnerIdType { get; set; }
        public Nullable<System.Guid> TransferHistoryId { get; set; }
    
        public virtual BusinessUnitBase BusinessUnitBase { get; set; }
        public virtual TransferHistoryBase TransferHistoryBase { get; set; }
        public virtual OwnerBase OwnerBase { get; set; }
    }
}
