//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRMOntology.DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class BusinessUnitBase
    {
        public BusinessUnitBase()
        {
            this.AccountBases = new HashSet<AccountBase>();
            this.ActivityPointerBases = new HashSet<ActivityPointerBase>();
            this.ActivityPointerBases1 = new HashSet<ActivityPointerBase>();
            this.CalendarBases = new HashSet<CalendarBase>();
            this.ConnectionBases = new HashSet<ConnectionBase>();
            this.ContactBases = new HashSet<ContactBase>();
            this.EntitlementBases = new HashSet<EntitlementBase>();
            this.EquipmentBases = new HashSet<EquipmentBase>();
            this.IncidentBases = new HashSet<IncidentBase>();
            this.LeadBases = new HashSet<LeadBase>();
            this.OpportunityBases = new HashSet<OpportunityBase>();
            this.BusinessUnitBase1 = new HashSet<BusinessUnitBase>();
            this.ContractBases = new HashSet<ContractBase>();
            this.SocialProfileBases = new HashSet<SocialProfileBase>();
            this.SystemUserBases = new HashSet<SystemUserBase>();
            this.CampaignBases = new HashSet<CampaignBase>();
            this.TeamBases = new HashSet<TeamBase>();
            this.AnnotationBases = new HashSet<AnnotationBase>();
        }
    
        public System.Guid BusinessUnitId { get; set; }
        public System.Guid OrganizationId { get; set; }
        public Nullable<System.Guid> UserGroupId { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public string DivisionName { get; set; }
        public string FileAsName { get; set; }
        public string TickerSymbol { get; set; }
        public string StockExchange { get; set; }
        public Nullable<int> UTCOffset { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public Nullable<double> CreditLimit { get; set; }
        public string CostCenter { get; set; }
        public string WebSiteUrl { get; set; }
        public string FtpSiteUrl { get; set; }
        public string EMailAddress { get; set; }
        public Nullable<int> InheritanceMask { get; set; }
        public Nullable<System.Guid> CreatedBy { get; set; }
        public Nullable<System.Guid> ModifiedBy { get; set; }
        public Nullable<bool> WorkflowSuspended { get; set; }
        public Nullable<System.Guid> ParentBusinessUnitId { get; set; }
        public Nullable<bool> IsDisabled { get; set; }
        public string DisabledReason { get; set; }
        public byte[] VersionNumber { get; set; }
        public string Picture { get; set; }
        public Nullable<System.Guid> CalendarId { get; set; }
        public Nullable<System.DateTime> OverriddenCreatedOn { get; set; }
        public Nullable<int> ImportSequenceNumber { get; set; }
        public Nullable<decimal> ExchangeRate { get; set; }
        public Nullable<System.Guid> ModifiedOnBehalfBy { get; set; }
        public Nullable<System.Guid> CreatedOnBehalfBy { get; set; }
        public Nullable<System.Guid> TransactionCurrencyId { get; set; }
        public System.Guid TransferHistoryId { get; set; }
    
        public virtual ICollection<AccountBase> AccountBases { get; set; }
        public virtual ICollection<ActivityPointerBase> ActivityPointerBases { get; set; }
        public virtual ICollection<ActivityPointerBase> ActivityPointerBases1 { get; set; }
        public virtual ICollection<CalendarBase> CalendarBases { get; set; }
        public virtual ICollection<ConnectionBase> ConnectionBases { get; set; }
        public virtual ICollection<ContactBase> ContactBases { get; set; }
        public virtual ICollection<EntitlementBase> EntitlementBases { get; set; }
        public virtual ICollection<EquipmentBase> EquipmentBases { get; set; }
        public virtual ICollection<IncidentBase> IncidentBases { get; set; }
        public virtual ICollection<LeadBase> LeadBases { get; set; }
        public virtual ICollection<OpportunityBase> OpportunityBases { get; set; }
        public virtual ICollection<BusinessUnitBase> BusinessUnitBase1 { get; set; }
        public virtual BusinessUnitBase BusinessUnitBase2 { get; set; }
        public virtual ICollection<ContractBase> ContractBases { get; set; }
        public virtual ICollection<SocialProfileBase> SocialProfileBases { get; set; }
        public virtual ICollection<SystemUserBase> SystemUserBases { get; set; }
        public virtual CalendarBase CalendarBase { get; set; }
        public virtual ICollection<CampaignBase> CampaignBases { get; set; }
        public virtual TransferHistoryBase TransferHistoryBase { get; set; }
        public virtual TransactionCurrencyBase TransactionCurrencyBase { get; set; }
        public virtual ICollection<TeamBase> TeamBases { get; set; }
        public virtual ICollection<AnnotationBase> AnnotationBases { get; set; }
    }
}
