//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRMOntology.DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class CalendarBase
    {
        public CalendarBase()
        {
            this.BusinessUnitBases = new HashSet<BusinessUnitBase>();
            this.CalendarBase1 = new HashSet<CalendarBase>();
            this.EquipmentBases = new HashSet<EquipmentBase>();
            this.OrganizationBases = new HashSet<OrganizationBase>();
            this.ServiceBases = new HashSet<ServiceBase>();
            this.SystemUserBases = new HashSet<SystemUserBase>();
        }
    
        public Nullable<System.Guid> ModifiedBy { get; set; }
        public System.Guid CalendarId { get; set; }
        public string Description { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public string Name { get; set; }
        public Nullable<System.Guid> BusinessUnitId { get; set; }
        public byte[] VersionNumber { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public Nullable<System.Guid> CreatedBy { get; set; }
        public Nullable<System.Guid> PrimaryUserId { get; set; }
        public System.Guid OrganizationId { get; set; }
        public bool IsShared { get; set; }
        public Nullable<System.Guid> ModifiedOnBehalfBy { get; set; }
        public Nullable<System.Guid> CreatedOnBehalfBy { get; set; }
        public Nullable<System.Guid> HolidayScheduleCalendarId { get; set; }
        public int Type { get; set; }
        public Nullable<System.Guid> TransferHistoryId { get; set; }
    
        public virtual BusinessUnitBase BusinessUnitBase { get; set; }
        public virtual ICollection<BusinessUnitBase> BusinessUnitBases { get; set; }
        public virtual ICollection<CalendarBase> CalendarBase1 { get; set; }
        public virtual CalendarBase CalendarBase2 { get; set; }
        public virtual ICollection<EquipmentBase> EquipmentBases { get; set; }
        public virtual ICollection<OrganizationBase> OrganizationBases { get; set; }
        public virtual ICollection<ServiceBase> ServiceBases { get; set; }
        public virtual ICollection<SystemUserBase> SystemUserBases { get; set; }
        public virtual TransferHistoryBase TransferHistoryBase { get; set; }
    }
}
