//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRMOntology.DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class CampaignBase
    {
        public CampaignBase()
        {
            this.LeadBases = new HashSet<LeadBase>();
            this.OpportunityBases = new HashSet<OpportunityBase>();
            this.CampaignItemBases = new HashSet<CampaignItemBase>();
        }
    
        public Nullable<int> TypeCode { get; set; }
        public Nullable<System.DateTime> ProposedEnd { get; set; }
        public Nullable<decimal> BudgetedCost { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public string PromotionCodeName { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public Nullable<System.Guid> PriceListId { get; set; }
        public Nullable<int> StatusCode { get; set; }
        public Nullable<System.Guid> CreatedBy { get; set; }
        public Nullable<bool> IsTemplate { get; set; }
        public System.Guid CampaignId { get; set; }
        public Nullable<System.DateTime> ActualStart { get; set; }
        public Nullable<System.Guid> OwningBusinessUnit { get; set; }
        public Nullable<decimal> TotalActualCost { get; set; }
        public string Message { get; set; }
        public Nullable<System.Guid> ModifiedBy { get; set; }
        public Nullable<decimal> ExpectedRevenue { get; set; }
        public byte[] VersionNumber { get; set; }
        public string CodeName { get; set; }
        public Nullable<System.DateTime> ProposedStart { get; set; }
        public string Objective { get; set; }
        public Nullable<System.DateTime> ActualEnd { get; set; }
        public int StateCode { get; set; }
        public Nullable<decimal> OtherCost { get; set; }
        public string Description { get; set; }
        public Nullable<decimal> TotalCampaignActivityActualCost { get; set; }
        public Nullable<int> ExpectedResponse { get; set; }
        public string Name { get; set; }
        public Nullable<decimal> ExchangeRate { get; set; }
        public Nullable<int> TimeZoneRuleVersionNumber { get; set; }
        public Nullable<System.Guid> TransactionCurrencyId { get; set; }
        public Nullable<int> ImportSequenceNumber { get; set; }
        public Nullable<System.DateTime> OverriddenCreatedOn { get; set; }
        public Nullable<int> UTCConversionTimeZoneCode { get; set; }
        public Nullable<decimal> TotalCampaignActivityActualCost_Base { get; set; }
        public Nullable<decimal> BudgetedCost_Base { get; set; }
        public Nullable<decimal> ExpectedRevenue_Base { get; set; }
        public Nullable<decimal> OtherCost_Base { get; set; }
        public Nullable<decimal> TotalActualCost_Base { get; set; }
        public System.Guid OwnerId { get; set; }
        public Nullable<System.Guid> ModifiedOnBehalfBy { get; set; }
        public Nullable<System.Guid> CreatedOnBehalfBy { get; set; }
        public int OwnerIdType { get; set; }
        public Nullable<System.Guid> StageId { get; set; }
        public Nullable<System.Guid> ProcessId { get; set; }
        public Nullable<System.Guid> EntityImageId { get; set; }
        public Nullable<System.Guid> TransferHistoryId { get; set; }
    
        public virtual BusinessUnitBase BusinessUnitBase { get; set; }
        public virtual ICollection<LeadBase> LeadBases { get; set; }
        public virtual ICollection<OpportunityBase> OpportunityBases { get; set; }
        public virtual ICollection<CampaignItemBase> CampaignItemBases { get; set; }
        public virtual TransferHistoryBase TransferHistoryBase { get; set; }
        public virtual OwnerBase OwnerBase { get; set; }
        public virtual PriceLevelBase PriceLevelBase { get; set; }
        public virtual TransactionCurrencyBase TransactionCurrencyBase { get; set; }
    }
}
