//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRMOntology.DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class ConnectionRoleBaseId
    {
        public ConnectionRoleBaseId()
        {
            this.ConnectionBases = new HashSet<ConnectionBase>();
            this.ConnectionBases1 = new HashSet<ConnectionBase>();
            this.ConnectionRoleAssociations = new HashSet<ConnectionRoleAssociation>();
        }
    
        public System.Guid ConnectionRoleId { get; set; }
        public Nullable<System.Guid> TransferHistoryId { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
    
        public virtual ICollection<ConnectionBase> ConnectionBases { get; set; }
        public virtual ICollection<ConnectionBase> ConnectionBases1 { get; set; }
        public virtual ICollection<ConnectionRoleAssociation> ConnectionRoleAssociations { get; set; }
        public virtual TransferHistoryBase TransferHistoryBase { get; set; }
    }
}
