//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRMOntology.DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class ConnectionBase
    {
        public ConnectionBase()
        {
            this.ConnectionBase1 = new HashSet<ConnectionBase>();
        }
    
        public Nullable<System.Guid> Record2RoleId { get; set; }
        public Nullable<System.Guid> ModifiedBy { get; set; }
        public Nullable<System.Guid> Record2Id { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<System.Guid> ModifiedOnBehalfBy { get; set; }
        public System.Guid ConnectionId { get; set; }
        public bool IsMaster { get; set; }
        public System.Guid OwnerId { get; set; }
        public byte[] VersionNumber { get; set; }
        public Nullable<int> Record2ObjectTypeCode { get; set; }
        public Nullable<int> ImportSequenceNumber { get; set; }
        public int StateCode { get; set; }
        public string Description { get; set; }
        public Nullable<System.DateTime> EffectiveStart { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public Nullable<System.Guid> TransactionCurrencyId { get; set; }
        public Nullable<System.Guid> OwningBusinessUnit { get; set; }
        public Nullable<System.DateTime> OverriddenCreatedOn { get; set; }
        public Nullable<System.Guid> Record1Id { get; set; }
        public Nullable<int> StatusCode { get; set; }
        public Nullable<System.Guid> CreatedOnBehalfBy { get; set; }
        public Nullable<int> Record1ObjectTypeCode { get; set; }
        public Nullable<System.Guid> RelatedConnectionId { get; set; }
        public Nullable<System.Guid> Record1RoleId { get; set; }
        public Nullable<System.Guid> CreatedBy { get; set; }
        public Nullable<System.DateTime> EffectiveEnd { get; set; }
        public Nullable<decimal> ExchangeRate { get; set; }
        public string Record2IdName { get; set; }
        public string Record1IdName { get; set; }
        public int OwnerIdType { get; set; }
        public Nullable<int> Record2IdObjectTypeCode { get; set; }
        public Nullable<int> Record1IdObjectTypeCode { get; set; }
        public Nullable<System.Guid> EntityImageId { get; set; }
        public Nullable<System.Guid> TransferHistoryId { get; set; }
    
        public virtual BusinessUnitBase BusinessUnitBase { get; set; }
        public virtual ICollection<ConnectionBase> ConnectionBase1 { get; set; }
        public virtual ConnectionBase ConnectionBase2 { get; set; }
        public virtual ConnectionRoleBaseId ConnectionRoleBaseId { get; set; }
        public virtual ConnectionRoleBaseId ConnectionRoleBaseId1 { get; set; }
        public virtual TransferHistoryBase TransferHistoryBase { get; set; }
        public virtual OwnerBase OwnerBase { get; set; }
        public virtual TransactionCurrencyBase TransactionCurrencyBase { get; set; }
    }
}
