//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRMOntology.DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class ContractBase
    {
        public ContractBase()
        {
            this.IncidentBases = new HashSet<IncidentBase>();
            this.ContractDetailBases = new HashSet<ContractDetailBase>();
            this.ContractBase1 = new HashSet<ContractBase>();
        }
    
        public System.Guid ContractId { get; set; }
        public Nullable<System.Guid> OwningBusinessUnit { get; set; }
        public Nullable<int> ContractServiceLevelCode { get; set; }
        public Nullable<System.Guid> ServiceAddress { get; set; }
        public Nullable<System.Guid> BillToAddress { get; set; }
        public string ContractNumber { get; set; }
        public System.DateTime ActiveOn { get; set; }
        public System.DateTime ExpiresOn { get; set; }
        public Nullable<System.DateTime> CancelOn { get; set; }
        public string Title { get; set; }
        public string ContractLanguage { get; set; }
        public Nullable<System.DateTime> BillingStartOn { get; set; }
        public string EffectivityCalendar { get; set; }
        public Nullable<System.DateTime> BillingEndOn { get; set; }
        public Nullable<int> BillingFrequencyCode { get; set; }
        public Nullable<System.Guid> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<System.Guid> ModifiedBy { get; set; }
        public Nullable<int> AllotmentTypeCode { get; set; }
        public Nullable<bool> UseDiscountAsPercentage { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public Nullable<decimal> TotalPrice { get; set; }
        public byte[] VersionNumber { get; set; }
        public Nullable<decimal> TotalDiscount { get; set; }
        public int StateCode { get; set; }
        public Nullable<decimal> NetPrice { get; set; }
        public Nullable<int> StatusCode { get; set; }
        public Nullable<System.Guid> OriginatingContract { get; set; }
        public Nullable<int> Duration { get; set; }
        public Nullable<int> TimeZoneRuleVersionNumber { get; set; }
        public Nullable<System.DateTime> OverriddenCreatedOn { get; set; }
        public Nullable<int> ImportSequenceNumber { get; set; }
        public Nullable<int> UTCConversionTimeZoneCode { get; set; }
        public Nullable<System.Guid> TransactionCurrencyId { get; set; }
        public Nullable<decimal> ExchangeRate { get; set; }
        public Nullable<decimal> TotalDiscount_Base { get; set; }
        public Nullable<decimal> NetPrice_Base { get; set; }
        public Nullable<decimal> TotalPrice_Base { get; set; }
        public Nullable<System.Guid> CreatedOnBehalfBy { get; set; }
        public Nullable<System.Guid> CustomerId { get; set; }
        public Nullable<System.Guid> ModifiedOnBehalfBy { get; set; }
        public System.Guid OwnerId { get; set; }
        public Nullable<System.Guid> BillingCustomerId { get; set; }
        public Nullable<int> CustomerIdType { get; set; }
        public int OwnerIdType { get; set; }
        public Nullable<int> BillingCustomerIdType { get; set; }
        public string CustomerIdName { get; set; }
        public string BillingCustomerIdName { get; set; }
        public string CustomerIdYomiName { get; set; }
        public string BillingCustomerIdYomiName { get; set; }
        public Nullable<System.Guid> EntityImageId { get; set; }
        public Nullable<System.Guid> TransferHistoryId { get; set; }
    
        public virtual BusinessUnitBase BusinessUnitBase { get; set; }
        public virtual ICollection<IncidentBase> IncidentBases { get; set; }
        public virtual ICollection<ContractDetailBase> ContractDetailBases { get; set; }
        public virtual ICollection<ContractBase> ContractBase1 { get; set; }
        public virtual ContractBase ContractBase2 { get; set; }
        public virtual CustomerAddressBase CustomerAddressBase { get; set; }
        public virtual CustomerAddressBase CustomerAddressBase1 { get; set; }
        public virtual TransferHistoryBase TransferHistoryBase { get; set; }
        public virtual OwnerBase OwnerBase { get; set; }
        public virtual TransactionCurrencyBase TransactionCurrencyBase { get; set; }
    }
}
