//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRMOntology.DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class EntitlementBase
    {
        public EntitlementBase()
        {
            this.IncidentBases = new HashSet<IncidentBase>();
        }
    
        public Nullable<System.Guid> SLAId { get; set; }
        public Nullable<System.Guid> ProcessId { get; set; }
        public Nullable<decimal> RemainingTerms { get; set; }
        public Nullable<int> ImportSequenceNumber { get; set; }
        public string Description { get; set; }
        public byte[] VersionNumber { get; set; }
        public Nullable<System.Guid> StageId { get; set; }
        public Nullable<int> StatusCode { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public Nullable<int> KbAccessLevel { get; set; }
        public Nullable<System.Guid> TransactionCurrencyId { get; set; }
        public Nullable<System.Guid> CustomerId { get; set; }
        public Nullable<System.Guid> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<System.Guid> ModifiedOnBehalfBy { get; set; }
        public string Name { get; set; }
        public Nullable<System.Guid> OwningBusinessUnit { get; set; }
        public Nullable<System.Guid> ModifiedBy { get; set; }
        public System.Guid EntitlementId { get; set; }
        public Nullable<int> AllocationTypeCode { get; set; }
        public Nullable<System.DateTime> OverriddenCreatedOn { get; set; }
        public Nullable<System.Guid> CreatedOnBehalfBy { get; set; }
        public Nullable<decimal> TotalTerms { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public Nullable<int> TimeZoneRuleVersionNumber { get; set; }
        public Nullable<int> DecreaseRemainingOn { get; set; }
        public Nullable<int> StateCode { get; set; }
        public Nullable<int> UTCConversionTimeZoneCode { get; set; }
        public Nullable<bool> RestrictCaseCreation { get; set; }
        public Nullable<decimal> ExchangeRate { get; set; }
        public System.Guid OwnerId { get; set; }
        public Nullable<System.Guid> AccountId { get; set; }
        public Nullable<System.Guid> ContactId { get; set; }
        public string CustomerIdName { get; set; }
        public string AccountIdName { get; set; }
        public string ContactIdName { get; set; }
        public Nullable<int> OwnerIdType { get; set; }
        public Nullable<int> CustomerIdType { get; set; }
        public string AccountIdYomiName { get; set; }
        public string ContactIdYomiName { get; set; }
        public string CustomerIdYomiName { get; set; }
        public Nullable<System.Guid> TransferHistoryId { get; set; }
    
        public virtual AccountBase AccountBase { get; set; }
        public virtual BusinessUnitBase BusinessUnitBase { get; set; }
        public virtual ContactBase ContactBase { get; set; }
        public virtual ICollection<IncidentBase> IncidentBases { get; set; }
        public virtual TransferHistoryBase TransferHistoryBase { get; set; }
        public virtual OwnerBase OwnerBase { get; set; }
        public virtual TransactionCurrencyBase TransactionCurrencyBase { get; set; }
    }
}
