//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRMOntology.DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class EquipmentBase
    {
        public EquipmentBase()
        {
            this.AccountBases = new HashSet<AccountBase>();
            this.ContactBases = new HashSet<ContactBase>();
        }
    
        public System.Guid EquipmentId { get; set; }
        public Nullable<System.Guid> SiteId { get; set; }
        public Nullable<System.Guid> ModifiedBy { get; set; }
        public Nullable<System.Guid> CreatedBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public System.Guid BusinessUnitId { get; set; }
        public string Skills { get; set; }
        public byte[] VersionNumber { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public int TimeZoneCode { get; set; }
        public Nullable<bool> DisplayInServiceViews { get; set; }
        public Nullable<bool> IsDisabled { get; set; }
        public string Name { get; set; }
        public System.Guid CalendarId { get; set; }
        public string Description { get; set; }
        public string EMailAddress { get; set; }
        public System.Guid OrganizationId { get; set; }
        public Nullable<int> ImportSequenceNumber { get; set; }
        public Nullable<System.DateTime> OverriddenCreatedOn { get; set; }
        public Nullable<int> TimeZoneRuleVersionNumber { get; set; }
        public Nullable<int> UTCConversionTimeZoneCode { get; set; }
        public Nullable<decimal> ExchangeRate { get; set; }
        public Nullable<System.Guid> ModifiedOnBehalfBy { get; set; }
        public Nullable<System.Guid> CreatedOnBehalfBy { get; set; }
        public Nullable<System.Guid> TransactionCurrencyId { get; set; }
        public Nullable<System.Guid> TransferHistoryId { get; set; }
    
        public virtual ICollection<AccountBase> AccountBases { get; set; }
        public virtual BusinessUnitBase BusinessUnitBase { get; set; }
        public virtual CalendarBase CalendarBase { get; set; }
        public virtual ICollection<ContactBase> ContactBases { get; set; }
        public virtual TransferHistoryBase TransferHistoryBase { get; set; }
        public virtual SiteBase SiteBase { get; set; }
        public virtual TransactionCurrencyBase TransactionCurrencyBase { get; set; }
    }
}
