//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRMOntology.DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class IncidentBase
    {
        public IncidentBase()
        {
            this.LeadBases = new HashSet<LeadBase>();
        }
    
        public System.Guid IncidentId { get; set; }
        public Nullable<System.Guid> OwningBusinessUnit { get; set; }
        public Nullable<System.Guid> ContractDetailId { get; set; }
        public Nullable<System.Guid> SubjectId { get; set; }
        public Nullable<System.Guid> ContractId { get; set; }
        public Nullable<int> ActualServiceUnits { get; set; }
        public Nullable<int> CaseOriginCode { get; set; }
        public Nullable<int> BilledServiceUnits { get; set; }
        public Nullable<int> CaseTypeCode { get; set; }
        public string ProductSerialNumber { get; set; }
        public string Title { get; set; }
        public Nullable<System.Guid> ProductId { get; set; }
        public Nullable<int> ContractServiceLevelCode { get; set; }
        public string Description { get; set; }
        public Nullable<bool> IsDecrementing { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public string TicketNumber { get; set; }
        public Nullable<int> PriorityCode { get; set; }
        public Nullable<int> CustomerSatisfactionCode { get; set; }
        public Nullable<int> IncidentStageCode { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public Nullable<System.Guid> CreatedBy { get; set; }
        public Nullable<System.DateTime> FollowupBy { get; set; }
        public Nullable<System.Guid> ModifiedBy { get; set; }
        public byte[] VersionNumber { get; set; }
        public int StateCode { get; set; }
        public Nullable<int> SeverityCode { get; set; }
        public Nullable<int> StatusCode { get; set; }
        public Nullable<System.Guid> ResponsibleContactId { get; set; }
        public Nullable<System.Guid> KbArticleId { get; set; }
        public Nullable<int> TimeZoneRuleVersionNumber { get; set; }
        public Nullable<int> ImportSequenceNumber { get; set; }
        public Nullable<int> UTCConversionTimeZoneCode { get; set; }
        public Nullable<System.DateTime> OverriddenCreatedOn { get; set; }
        public Nullable<decimal> ExchangeRate { get; set; }
        public Nullable<System.Guid> ModifiedOnBehalfBy { get; set; }
        public Nullable<System.Guid> TransactionCurrencyId { get; set; }
        public Nullable<System.Guid> CreatedOnBehalfBy { get; set; }
        public Nullable<System.Guid> CustomerId { get; set; }
        public System.Guid OwnerId { get; set; }
        public int OwnerIdType { get; set; }
        public Nullable<int> CustomerIdType { get; set; }
        public string CustomerIdName { get; set; }
        public string CustomerIdYomiName { get; set; }
        public Nullable<bool> ActivitiesComplete { get; set; }
        public Nullable<System.Guid> StageId { get; set; }
        public Nullable<System.Guid> ExistingCase { get; set; }
        public Nullable<int> ServiceStage { get; set; }
        public Nullable<bool> CheckEmail { get; set; }
        public Nullable<bool> FollowUpTaskCreated { get; set; }
        public Nullable<System.Guid> EntityImageId { get; set; }
        public Nullable<System.Guid> ProcessId { get; set; }
        public Nullable<System.Guid> SLAInvokedId { get; set; }
        public Nullable<bool> RouteCase { get; set; }
        public Nullable<bool> IsEscalated { get; set; }
        public Nullable<bool> CustomerContacted { get; set; }
        public Nullable<System.Guid> MasterId { get; set; }
        public Nullable<bool> BlockedProfile { get; set; }
        public Nullable<System.Guid> PrimaryContactId { get; set; }
        public Nullable<double> SentimentValue { get; set; }
        public Nullable<bool> Merged { get; set; }
        public Nullable<System.DateTime> ResponseBy { get; set; }
        public Nullable<System.DateTime> EscalatedOn { get; set; }
        public Nullable<System.Guid> ParentCaseId { get; set; }
        public Nullable<System.Guid> SocialProfileId { get; set; }
        public Nullable<int> MessageTypeCode { get; set; }
        public Nullable<int> ResolveBySLAStatus { get; set; }
        public Nullable<System.DateTime> ResolveBy { get; set; }
        public Nullable<double> InfluenceScore { get; set; }
        public Nullable<System.Guid> EntitlementId { get; set; }
        public Nullable<int> FirstResponseSLAStatus { get; set; }
        public Nullable<bool> FirstResponseSent { get; set; }
        public Nullable<System.Guid> TransferHistoryId { get; set; }
    
        public virtual BusinessUnitBase BusinessUnitBase { get; set; }
        public virtual ContactBase ContactBase { get; set; }
        public virtual ContactBase ContactBase1 { get; set; }
        public virtual ContractBase ContractBase { get; set; }
        public virtual ContractDetailBase ContractDetailBase { get; set; }
        public virtual EntitlementBase EntitlementBase { get; set; }
        public virtual TransferHistoryBase TransferHistoryBase { get; set; }
        public virtual KbArticleBase KbArticleBase { get; set; }
        public virtual ICollection<LeadBase> LeadBases { get; set; }
        public virtual OwnerBase OwnerBase { get; set; }
        public virtual ProductBase ProductBase { get; set; }
        public virtual SocialProfileBase SocialProfileBase { get; set; }
        public virtual SubjectBase SubjectBase { get; set; }
        public virtual TransactionCurrencyBase TransactionCurrencyBase { get; set; }
    }
}
