//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRMOntology.DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class KbArticleTemplateBase
    {
        public System.Guid KbArticleTemplateId { get; set; }
        public string StructureXml { get; set; }
        public System.Guid OrganizationId { get; set; }
        public string FormatXml { get; set; }
        public string Title { get; set; }
        public byte[] VersionNumber { get; set; }
        public string Description { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<System.Guid> CreatedBy { get; set; }
        public Nullable<System.Guid> ModifiedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public Nullable<System.DateTime> OverriddenCreatedOn { get; set; }
        public Nullable<int> LanguageCode { get; set; }
        public Nullable<int> ImportSequenceNumber { get; set; }
        public bool IsCustomizable { get; set; }
        public Nullable<System.Guid> ModifiedOnBehalfBy { get; set; }
        public System.Guid SolutionId { get; set; }
        public Nullable<System.Guid> CreatedOnBehalfBy { get; set; }
        public int ComponentState { get; set; }
        public Nullable<System.Guid> SupportingSolutionId { get; set; }
        public System.Guid KbArticleTemplateIdUnique { get; set; }
        public bool IsManaged { get; set; }
        public System.DateTime OverwriteTime { get; set; }
        public string IntroducedVersion { get; set; }
        public Nullable<System.Guid> TransferHistoryId { get; set; }
    
        public virtual TransferHistoryBase TransferHistoryBase { get; set; }
    }
}
