//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRMOntology.DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrganizationBase
    {
        public System.Guid OrganizationId { get; set; }
        public string Name { get; set; }
        public Nullable<System.Guid> UserGroupId { get; set; }
        public Nullable<System.Guid> PrivilegeUserGroupId { get; set; }
        public int FiscalPeriodType { get; set; }
        public Nullable<System.DateTime> FiscalCalendarStart { get; set; }
        public int DateFormatCode { get; set; }
        public int TimeFormatCode { get; set; }
        public string CurrencySymbol { get; set; }
        public int WeekStartDayCode { get; set; }
        public string DateSeparator { get; set; }
        public int FullNameConventionCode { get; set; }
        public int NegativeFormatCode { get; set; }
        public string NumberFormat { get; set; }
        public Nullable<bool> IsDisabled { get; set; }
        public string DisabledReason { get; set; }
        public string KbPrefix { get; set; }
        public Nullable<int> CurrentKbNumber { get; set; }
        public string CasePrefix { get; set; }
        public Nullable<int> CurrentCaseNumber { get; set; }
        public string ContractPrefix { get; set; }
        public Nullable<int> CurrentContractNumber { get; set; }
        public string QuotePrefix { get; set; }
        public Nullable<int> CurrentQuoteNumber { get; set; }
        public string OrderPrefix { get; set; }
        public Nullable<int> CurrentOrderNumber { get; set; }
        public string InvoicePrefix { get; set; }
        public Nullable<int> CurrentInvoiceNumber { get; set; }
        public Nullable<int> UniqueSpecifierLength { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public string FiscalYearFormat { get; set; }
        public string FiscalPeriodFormat { get; set; }
        public string FiscalYearPeriodConnect { get; set; }
        public Nullable<int> LanguageCode { get; set; }
        public Nullable<int> SortId { get; set; }
        public string DateFormatString { get; set; }
        public string TimeFormatString { get; set; }
        public int PricingDecimalPrecision { get; set; }
        public Nullable<bool> ShowWeekNumber { get; set; }
        public Nullable<int> NextTrackingNumber { get; set; }
        public byte TagMaxAggressiveCycles { get; set; }
        public string TokenKey { get; set; }
        public Nullable<System.Guid> SystemUserId { get; set; }
        public Nullable<System.Guid> CreatedBy { get; set; }
        public Nullable<bool> GrantAccessToNetworkService { get; set; }
        public bool AllowOutlookScheduledSyncs { get; set; }
        public bool AllowMarketingEmailExecution { get; set; }
        public Nullable<System.Guid> SqlAccessGroupId { get; set; }
        public int CurrencyFormatCode { get; set; }
        public bool FiscalSettingsUpdated { get; set; }
        public Nullable<System.Guid> ReportingGroupId { get; set; }
        public Nullable<short> TokenExpiry { get; set; }
        public bool ShareToPreviousOwnerOnAssign { get; set; }
        public Nullable<System.Guid> ModifiedBy { get; set; }
        public Nullable<System.Guid> IntegrationUserId { get; set; }
        public Nullable<int> TrackingTokenIdBase { get; set; }
        public Nullable<System.Guid> BusinessClosureCalendarId { get; set; }
        public Nullable<bool> AllowAutoUnsubscribeAcknowledgement { get; set; }
        public Nullable<bool> AllowAutoUnsubscribe { get; set; }
        public string Picture { get; set; }
        public byte[] VersionNumber { get; set; }
        public string TrackingPrefix { get; set; }
        public int MinOutlookSyncInterval { get; set; }
        public string BulkOperationPrefix { get; set; }
        public Nullable<bool> AllowAutoResponseCreation { get; set; }
        public Nullable<int> MaximumTrackingNumber { get; set; }
        public string CampaignPrefix { get; set; }
        public string SqlAccessGroupName { get; set; }
        public Nullable<int> CurrentCampaignNumber { get; set; }
        public byte FiscalYearDisplayCode { get; set; }
        public string SiteMapXml { get; set; }
        public Nullable<bool> IsRegistered { get; set; }
        public string ReportingGroupName { get; set; }
        public Nullable<int> CurrentBulkOperationNumber { get; set; }
        public string SchemaNamePrefix { get; set; }
        public bool IgnoreInternalEmail { get; set; }
        public int TagPollingPeriod { get; set; }
        public Nullable<byte> TrackingTokenIdDigits { get; set; }
        public string NumberGroupFormat { get; set; }
        public int LongDateFormatCode { get; set; }
        public Nullable<int> UTCConversionTimeZoneCode { get; set; }
        public Nullable<int> TimeZoneRuleVersionNumber { get; set; }
        public int CurrentImportSequenceNumber { get; set; }
        public string ParsedTablePrefix { get; set; }
        public string V3CalloutConfigHash { get; set; }
        public bool IsFiscalPeriodMonthBased { get; set; }
        public int LocaleId { get; set; }
        public string ParsedTableColumnPrefix { get; set; }
        public Nullable<System.Guid> SupportUserId { get; set; }
        public string AMDesignator { get; set; }
        public int CurrencyDisplayOption { get; set; }
        public int MinAddressBookSyncInterval { get; set; }
        public bool IsDuplicateDetectionEnabledForOnlineCreateUpdate { get; set; }
        public string FeatureSet { get; set; }
        public string BlockedAttachments { get; set; }
        public bool IsDuplicateDetectionEnabledForOfflineSync { get; set; }
        public bool AllowOfflineScheduledSyncs { get; set; }
        public bool AllowUnresolvedPartiesOnEmailSend { get; set; }
        public string TimeSeparator { get; set; }
        public int CurrentParsedTableNumber { get; set; }
        public int MinOfflineSyncInterval { get; set; }
        public bool AllowWebExcelExport { get; set; }
        public string ReferenceSiteMapXml { get; set; }
        public bool IsDuplicateDetectionEnabledForImport { get; set; }
        public Nullable<int> CalendarType { get; set; }
        public Nullable<bool> SQMEnabled { get; set; }
        public int NegativeCurrencyFormatCode { get; set; }
        public bool AllowAddressBookSyncs { get; set; }
        public int ISVIntegrationCode { get; set; }
        public string DecimalSymbol { get; set; }
        public int MaxUploadFileSize { get; set; }
        public bool IsAppMode { get; set; }
        public bool EnablePricingOnCreate { get; set; }
        public bool IsSOPIntegrationEnabled { get; set; }
        public string PMDesignator { get; set; }
        public int CurrencyDecimalPrecision { get; set; }
        public int MaxAppointmentDurationDays { get; set; }
        public int EmailSendPollingPeriod { get; set; }
        public bool RenderSecureIFrameForEmail { get; set; }
        public string NumberSeparator { get; set; }
        public Nullable<System.Guid> PrivReportingGroupId { get; set; }
        public Nullable<System.Guid> BaseCurrencyId { get; set; }
        public int MaxRecordsForExportToExcel { get; set; }
        public string PrivReportingGroupName { get; set; }
        public int YearStartWeekCode { get; set; }
        public Nullable<bool> IsPresenceEnabled { get; set; }
        public bool IsDuplicateDetectionEnabled { get; set; }
        public int RecurrenceExpansionJobBatchInterval { get; set; }
        public Nullable<int> DefaultRecurrenceEndRangeType { get; set; }
        public Nullable<int> HashMinAddressCount { get; set; }
        public bool RequireApprovalForUserEmail { get; set; }
        public int RecurrenceDefaultNumberOfOccurrences { get; set; }
        public Nullable<System.Guid> ModifiedOnBehalfBy { get; set; }
        public bool RequireApprovalForQueueEmail { get; set; }
        public bool AllowEntityOnlyAudit { get; set; }
        public bool IsAuditEnabled { get; set; }
        public int RecurrenceExpansionSynchCreateMax { get; set; }
        public int GoalRollupExpiryTime { get; set; }
        public int BaseCurrencyPrecision { get; set; }
        public Nullable<int> FiscalPeriodFormatPeriod { get; set; }
        public bool AllowClientMessageBarAd { get; set; }
        public string InitialVersion { get; set; }
        public string HashFilterKeywords { get; set; }
        public int NextCustomObjectTypeCode { get; set; }
        public int ExpireSubscriptionsInDays { get; set; }
        public string OrgDbOrgSettings { get; set; }
        public int PastExpansionWindow { get; set; }
        public Nullable<bool> EnableSmartMatching { get; set; }
        public int MaxRecordsForLookupFilters { get; set; }
        public string BaseCurrencySymbol { get; set; }
        public int ReportScriptErrors { get; set; }
        public int RecurrenceExpansionJobBatchSize { get; set; }
        public int FutureExpansionWindow { get; set; }
        public bool GetStartedPaneContentEnabled { get; set; }
        public Nullable<System.Guid> SampleDataImportId { get; set; }
        public string BaseISOCurrencyCode { get; set; }
        public int GoalRollupFrequency { get; set; }
        public Nullable<System.Guid> CreatedOnBehalfBy { get; set; }
        public Nullable<int> HashDeltaSubjectCount { get; set; }
        public Nullable<int> HashMaxCount { get; set; }
        public Nullable<int> FiscalYearFormatYear { get; set; }
        public Nullable<int> FiscalYearFormatPrefix { get; set; }
        public Nullable<int> PinpointLanguageCode { get; set; }
        public Nullable<int> FiscalYearFormatSuffix { get; set; }
        public bool AllowUserFormModePreference { get; set; }
        public Nullable<int> MaximumActiveBusinessProcessFlowsAllowedPerEntity { get; set; }
        public Nullable<int> YammerGroupId { get; set; }
        public bool IsUserAccessAuditEnabled { get; set; }
        public bool IsDefaultCountryCodeCheckEnabled { get; set; }
        public Nullable<System.DateTime> MetadataSyncLastTimeOfNeverExpiredDeletedObjects { get; set; }
        public Nullable<int> IncomingEmailExchangeEmailRetrievalBatchSize { get; set; }
        public bool QuickFindRecordLimitEnabled { get; set; }
        public Nullable<bool> YammerOAuthAccessTokenExpired { get; set; }
        public bool UseSkypeProtocol { get; set; }
        public bool GenerateAlertsForErrors { get; set; }
        public string DefaultCountryCode { get; set; }
        public bool EmailCorrelationEnabled { get; set; }
        public int UserAccessAuditingInterval { get; set; }
        public bool IsAutoSaveEnabled { get; set; }
        public string DefaultEmailSettings { get; set; }
        public long MetadataSyncTimestamp { get; set; }
        public string YammerNetworkPermalink { get; set; }
        public int EmailConnectionChannel { get; set; }
        public Nullable<System.Guid> EntityImageId { get; set; }
        public bool NotifyMailboxOwnerOfEmailServerLevelAlerts { get; set; }
        public string BingMapsApiKey { get; set; }
        public bool GenerateAlertsForInformation { get; set; }
        public bool GenerateAlertsForWarnings { get; set; }
        public Nullable<int> YammerPostMethod { get; set; }
        public bool AllowUsersSeeAppdownloadMessage { get; set; }
        public bool UseReadForm { get; set; }
        public bool EnableBingMapsIntegration { get; set; }
        public string SignupOutlookDownloadFWLink { get; set; }
        public bool DisableSocialCare { get; set; }
        public Nullable<bool> CascadeStatusUpdate { get; set; }
        public Nullable<bool> RestrictStatusUpdate { get; set; }
        public Nullable<bool> SocialInsightsTermsAccepted { get; set; }
        public string SocialInsightsInstance { get; set; }
        public bool SuppressSLA { get; set; }
        public bool IsEmailServerProfileContentFilteringEnabled { get; set; }
        public bool IsMailboxInactiveBackoffEnabled { get; set; }
        public Nullable<System.Guid> TransferHistoryId { get; set; }
    
        public virtual CalendarBase CalendarBase { get; set; }
        public virtual TransactionCurrencyBase TransactionCurrencyBase { get; set; }
        public virtual TransferHistoryBase TransferHistoryBase { get; set; }
    }
}
