//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRMOntology.DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class OWLMapBase
    {
        public System.Guid OWLMapId { get; set; }
        public System.Guid TransferHistoryId { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public string FromTableName { get; set; }
        public System.Guid FromTablePKId { get; set; }
        public Nullable<System.Guid> ToOWLId { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
    }
}
