//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRMOntology.DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class OwnerBase
    {
        public OwnerBase()
        {
            this.AccountBases = new HashSet<AccountBase>();
            this.ActivityPointerBases = new HashSet<ActivityPointerBase>();
            this.CampaignBases = new HashSet<CampaignBase>();
            this.ConnectionBases = new HashSet<ConnectionBase>();
            this.ContactBases = new HashSet<ContactBase>();
            this.ContractBases = new HashSet<ContractBase>();
            this.EntitlementBases = new HashSet<EntitlementBase>();
            this.IncidentBases = new HashSet<IncidentBase>();
            this.LeadBases = new HashSet<LeadBase>();
            this.OpportunityBases = new HashSet<OpportunityBase>();
            this.SocialProfileBases = new HashSet<SocialProfileBase>();
            this.AnnotationBases = new HashSet<AnnotationBase>();
        }
    
        public int OwnerIdType { get; set; }
        public System.Guid OwnerId { get; set; }
        public string Name { get; set; }
        public byte[] VersionNumber { get; set; }
        public string YomiName { get; set; }
        public Nullable<System.Guid> TransferHistoryId { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
    
        public virtual ICollection<AccountBase> AccountBases { get; set; }
        public virtual ICollection<ActivityPointerBase> ActivityPointerBases { get; set; }
        public virtual ICollection<CampaignBase> CampaignBases { get; set; }
        public virtual ICollection<ConnectionBase> ConnectionBases { get; set; }
        public virtual ICollection<ContactBase> ContactBases { get; set; }
        public virtual ICollection<ContractBase> ContractBases { get; set; }
        public virtual ICollection<EntitlementBase> EntitlementBases { get; set; }
        public virtual ICollection<IncidentBase> IncidentBases { get; set; }
        public virtual ICollection<LeadBase> LeadBases { get; set; }
        public virtual ICollection<OpportunityBase> OpportunityBases { get; set; }
        public virtual TransferHistoryBase TransferHistoryBase { get; set; }
        public virtual ICollection<SocialProfileBase> SocialProfileBases { get; set; }
        public virtual ICollection<AnnotationBase> AnnotationBases { get; set; }
    }
}
