//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRMOntology.DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class PriceLevelBase
    {
        public PriceLevelBase()
        {
            this.AccountBases = new HashSet<AccountBase>();
            this.CampaignBases = new HashSet<CampaignBase>();
            this.ContactBases = new HashSet<ContactBase>();
            this.OpportunityBases = new HashSet<OpportunityBase>();
            this.ProductBases = new HashSet<ProductBase>();
        }
    
        public System.Guid PriceLevelId { get; set; }
        public System.Guid OrganizationId { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public Nullable<int> ShippingMethodCode { get; set; }
        public Nullable<System.DateTime> BeginDate { get; set; }
        public Nullable<int> PaymentMethodCode { get; set; }
        public Nullable<int> FreightTermsCode { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public Nullable<System.Guid> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<System.Guid> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public int StateCode { get; set; }
        public byte[] VersionNumber { get; set; }
        public Nullable<int> StatusCode { get; set; }
        public Nullable<int> ImportSequenceNumber { get; set; }
        public Nullable<System.Guid> TransactionCurrencyId { get; set; }
        public Nullable<System.DateTime> OverriddenCreatedOn { get; set; }
        public Nullable<int> TimeZoneRuleVersionNumber { get; set; }
        public Nullable<int> UTCConversionTimeZoneCode { get; set; }
        public Nullable<System.Guid> ModifiedOnBehalfBy { get; set; }
        public Nullable<decimal> ExchangeRate { get; set; }
        public Nullable<System.Guid> CreatedOnBehalfBy { get; set; }
        public Nullable<System.Guid> TransferHistoryId { get; set; }
    
        public virtual ICollection<AccountBase> AccountBases { get; set; }
        public virtual ICollection<CampaignBase> CampaignBases { get; set; }
        public virtual ICollection<ContactBase> ContactBases { get; set; }
        public virtual ICollection<OpportunityBase> OpportunityBases { get; set; }
        public virtual TransferHistoryBase TransferHistoryBase { get; set; }
        public virtual ICollection<ProductBase> ProductBases { get; set; }
        public virtual TransactionCurrencyBase TransactionCurrencyBase { get; set; }
    }
}
