//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRMOntology.DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductBase
    {
        public ProductBase()
        {
            this.CompetitorProducts = new HashSet<CompetitorProduct>();
            this.ContractDetailBases = new HashSet<ContractDetailBase>();
            this.IncidentBases = new HashSet<IncidentBase>();
        }
    
        public System.Guid ProductId { get; set; }
        public Nullable<System.Guid> DefaultUoMScheduleId { get; set; }
        public Nullable<System.Guid> SubjectId { get; set; }
        public System.Guid OrganizationId { get; set; }
        public string Name { get; set; }
        public Nullable<System.Guid> DefaultUoMId { get; set; }
        public Nullable<System.Guid> PriceLevelId { get; set; }
        public string Description { get; set; }
        public Nullable<int> ProductTypeCode { get; set; }
        public string ProductUrl { get; set; }
        public Nullable<decimal> Price { get; set; }
        public Nullable<bool> IsKit { get; set; }
        public string ProductNumber { get; set; }
        public string Size { get; set; }
        public Nullable<decimal> CurrentCost { get; set; }
        public Nullable<decimal> StockVolume { get; set; }
        public Nullable<decimal> StandardCost { get; set; }
        public Nullable<decimal> StockWeight { get; set; }
        public Nullable<int> QuantityDecimal { get; set; }
        public Nullable<decimal> QuantityOnHand { get; set; }
        public Nullable<bool> IsStockItem { get; set; }
        public string SupplierName { get; set; }
        public string VendorName { get; set; }
        public string VendorPartNumber { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public Nullable<System.Guid> CreatedBy { get; set; }
        public int StateCode { get; set; }
        public Nullable<System.Guid> ModifiedBy { get; set; }
        public Nullable<int> StatusCode { get; set; }
        public byte[] VersionNumber { get; set; }
        public Nullable<System.DateTime> OverriddenCreatedOn { get; set; }
        public Nullable<System.Guid> TransactionCurrencyId { get; set; }
        public Nullable<decimal> ExchangeRate { get; set; }
        public Nullable<int> UTCConversionTimeZoneCode { get; set; }
        public Nullable<int> ImportSequenceNumber { get; set; }
        public Nullable<int> TimeZoneRuleVersionNumber { get; set; }
        public Nullable<decimal> CurrentCost_Base { get; set; }
        public Nullable<decimal> Price_Base { get; set; }
        public Nullable<decimal> StandardCost_Base { get; set; }
        public Nullable<System.Guid> ModifiedOnBehalfBy { get; set; }
        public Nullable<System.Guid> CreatedOnBehalfBy { get; set; }
        public Nullable<System.Guid> StageId { get; set; }
        public Nullable<System.Guid> ProcessId { get; set; }
        public Nullable<System.Guid> EntityImageId { get; set; }
        public Nullable<System.Guid> TransferHistoryId { get; set; }
    
        public virtual ICollection<CompetitorProduct> CompetitorProducts { get; set; }
        public virtual ICollection<ContractDetailBase> ContractDetailBases { get; set; }
        public virtual ICollection<IncidentBase> IncidentBases { get; set; }
        public virtual PriceLevelBase PriceLevelBase { get; set; }
        public virtual TransferHistoryBase TransferHistoryBase { get; set; }
        public virtual SubjectBase SubjectBase { get; set; }
        public virtual TransactionCurrencyBase TransactionCurrencyBase { get; set; }
        public virtual UoMBase UoMBase { get; set; }
        public virtual UoMScheduleBase UoMScheduleBase { get; set; }
    }
}
