//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRMOntology.DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class ServiceBase
    {
        public ServiceBase()
        {
            this.AccountBases = new HashSet<AccountBase>();
            this.ActivityPointerBases = new HashSet<ActivityPointerBase>();
            this.ContactBases = new HashSet<ContactBase>();
        }
    
        public string Name { get; set; }
        public System.Guid OrganizationId { get; set; }
        public System.Guid ServiceId { get; set; }
        public Nullable<System.Guid> ModifiedBy { get; set; }
        public Nullable<int> AnchorOffset { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public int Duration { get; set; }
        public bool IsSchedulable { get; set; }
        public System.Guid StrategyId { get; set; }
        public byte[] VersionNumber { get; set; }
        public Nullable<System.Guid> CreatedBy { get; set; }
        public int InitialStatusCode { get; set; }
        public Nullable<System.Guid> CalendarId { get; set; }
        public Nullable<bool> ShowResources { get; set; }
        public string Granularity { get; set; }
        public string Description { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<bool> IsVisible { get; set; }
        public Nullable<int> ImportSequenceNumber { get; set; }
        public Nullable<System.DateTime> OverriddenCreatedOn { get; set; }
        public Nullable<System.Guid> ModifiedOnBehalfBy { get; set; }
        public Nullable<System.Guid> CreatedOnBehalfBy { get; set; }
        public Nullable<System.Guid> TransferHistoryId { get; set; }
    
        public virtual ICollection<AccountBase> AccountBases { get; set; }
        public virtual ICollection<ActivityPointerBase> ActivityPointerBases { get; set; }
        public virtual CalendarBase CalendarBase { get; set; }
        public virtual ICollection<ContactBase> ContactBases { get; set; }
        public virtual TransferHistoryBase TransferHistoryBase { get; set; }
    }
}
