//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRMOntology.DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class SocialProfileBase
    {
        public SocialProfileBase()
        {
            this.ActivityPointerBases = new HashSet<ActivityPointerBase>();
            this.IncidentBases = new HashSet<IncidentBase>();
        }
    
        public Nullable<bool> Blocked { get; set; }
        public Nullable<System.DateTime> OverriddenCreatedOn { get; set; }
        public Nullable<int> Community { get; set; }
        public Nullable<int> ImportSequenceNumber { get; set; }
        public System.Guid OwnerId { get; set; }
        public Nullable<int> TimeZoneRuleVersionNumber { get; set; }
        public Nullable<int> UTCConversionTimeZoneCode { get; set; }
        public int StateCode { get; set; }
        public Nullable<System.Guid> OwningBusinessUnit { get; set; }
        public Nullable<double> InfluenceScore { get; set; }
        public Nullable<System.Guid> CustomerId { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public Nullable<int> StatusCode { get; set; }
        public System.Guid SocialProfileId { get; set; }
        public Nullable<System.Guid> ModifiedOnBehalfBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<System.Guid> ModifiedBy { get; set; }
        public string ProfileFullName { get; set; }
        public Nullable<System.Guid> TransactionCurrencyId { get; set; }
        public Nullable<decimal> ExchangeRate { get; set; }
        public string ProfileName { get; set; }
        public byte[] VersionNumber { get; set; }
        public string ProfileLink { get; set; }
        public Nullable<System.Guid> CreatedBy { get; set; }
        public Nullable<System.Guid> CreatedOnBehalfBy { get; set; }
        public string UniqueProfileID { get; set; }
        public string CustomerIdName { get; set; }
        public Nullable<int> CustomerIdType { get; set; }
        public int OwnerIdType { get; set; }
        public string CustomerIdYomiName { get; set; }
        public Nullable<System.Guid> TransferHistoryId { get; set; }
    
        public virtual ICollection<ActivityPointerBase> ActivityPointerBases { get; set; }
        public virtual BusinessUnitBase BusinessUnitBase { get; set; }
        public virtual ICollection<IncidentBase> IncidentBases { get; set; }
        public virtual OwnerBase OwnerBase { get; set; }
        public virtual TransferHistoryBase TransferHistoryBase { get; set; }
        public virtual TransactionCurrencyBase TransactionCurrencyBase { get; set; }
    }
}
