//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRMOntology.DataAccessLayer
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CRMOntology_StagingEntities : DbContext
    {
        public CRMOntology_StagingEntities()
            : base("name=CRMOntology_StagingEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AccountBase> AccountBases { get; set; }
        public virtual DbSet<ActivityPartyBase> ActivityPartyBases { get; set; }
        public virtual DbSet<ActivityPointerBase> ActivityPointerBases { get; set; }
        public virtual DbSet<AppointmentBase> AppointmentBases { get; set; }
        public virtual DbSet<BusinessUnitBase> BusinessUnitBases { get; set; }
        public virtual DbSet<CalendarBase> CalendarBases { get; set; }
        public virtual DbSet<CampaignActivityBase> CampaignActivityBases { get; set; }
        public virtual DbSet<CampaignActivityItemBase> CampaignActivityItemBases { get; set; }
        public virtual DbSet<CampaignBase> CampaignBases { get; set; }
        public virtual DbSet<CampaignItemBase> CampaignItemBases { get; set; }
        public virtual DbSet<CampaignResponseBase> CampaignResponseBases { get; set; }
        public virtual DbSet<CompetitorBase> CompetitorBases { get; set; }
        public virtual DbSet<CompetitorProduct> CompetitorProducts { get; set; }
        public virtual DbSet<ConnectionBase> ConnectionBases { get; set; }
        public virtual DbSet<ConnectionRoleAssociation> ConnectionRoleAssociations { get; set; }
        public virtual DbSet<ConnectionRoleBase> ConnectionRoleBases { get; set; }
        public virtual DbSet<ConnectionRoleBaseId> ConnectionRoleBaseIds { get; set; }
        public virtual DbSet<ContactBase> ContactBases { get; set; }
        public virtual DbSet<ContractBase> ContractBases { get; set; }
        public virtual DbSet<ContractDetailBase> ContractDetailBases { get; set; }
        public virtual DbSet<CustomerAddressBase> CustomerAddressBases { get; set; }
        public virtual DbSet<EmailBase> EmailBases { get; set; }
        public virtual DbSet<EntitlementBase> EntitlementBases { get; set; }
        public virtual DbSet<EquipmentBase> EquipmentBases { get; set; }
        public virtual DbSet<FaxBase> FaxBases { get; set; }
        public virtual DbSet<IncidentBase> IncidentBases { get; set; }
        public virtual DbSet<KbArticleBase> KbArticleBases { get; set; }
        public virtual DbSet<KbArticleTemplateBase> KbArticleTemplateBases { get; set; }
        public virtual DbSet<LeadBase> LeadBases { get; set; }
        public virtual DbSet<LetterBase> LetterBases { get; set; }
        public virtual DbSet<OpportunityBase> OpportunityBases { get; set; }
        public virtual DbSet<OrganizationBase> OrganizationBases { get; set; }
        public virtual DbSet<OWLMapBase> OWLMapBases { get; set; }
        public virtual DbSet<OwnerBase> OwnerBases { get; set; }
        public virtual DbSet<PhoneCallBase> PhoneCallBases { get; set; }
        public virtual DbSet<PriceLevelBase> PriceLevelBases { get; set; }
        public virtual DbSet<ProductBase> ProductBases { get; set; }
        public virtual DbSet<ServiceBase> ServiceBases { get; set; }
        public virtual DbSet<SiteBase> SiteBases { get; set; }
        public virtual DbSet<SocialProfileBase> SocialProfileBases { get; set; }
        public virtual DbSet<SubjectBase> SubjectBases { get; set; }
        public virtual DbSet<SystemUserBase> SystemUserBases { get; set; }
        public virtual DbSet<TerritoryBase> TerritoryBases { get; set; }
        public virtual DbSet<TransactionCurrencyBase> TransactionCurrencyBases { get; set; }
        public virtual DbSet<TransferHistoryBase> TransferHistoryBases { get; set; }
        public virtual DbSet<UoMBase> UoMBases { get; set; }
        public virtual DbSet<UoMScheduleBase> UoMScheduleBases { get; set; }
        public virtual DbSet<TeamBase> TeamBases { get; set; }
        public virtual DbSet<TeamMembership> TeamMemberships { get; set; }
        public virtual DbSet<AnnotationBase> AnnotationBases { get; set; }
        public virtual DbSet<TaskBase> TaskBases { get; set; }
    }
}
