//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRMOntology.DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class SubjectBase
    {
        public SubjectBase()
        {
            this.IncidentBases = new HashSet<IncidentBase>();
            this.KbArticleBases = new HashSet<KbArticleBase>();
            this.ProductBases = new HashSet<ProductBase>();
            this.SubjectBase1 = new HashSet<SubjectBase>();
        }
    
        public System.Guid SubjectId { get; set; }
        public string Title { get; set; }
        public System.Guid OrganizationId { get; set; }
        public string Description { get; set; }
        public Nullable<System.Guid> ParentSubject { get; set; }
        public Nullable<int> FeatureMask { get; set; }
        public Nullable<System.Guid> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<System.Guid> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public byte[] VersionNumber { get; set; }
        public Nullable<int> ImportSequenceNumber { get; set; }
        public Nullable<System.DateTime> OverriddenCreatedOn { get; set; }
        public Nullable<System.Guid> ModifiedOnBehalfBy { get; set; }
        public Nullable<System.Guid> CreatedOnBehalfBy { get; set; }
        public Nullable<System.Guid> TransferHistoryId { get; set; }
    
        public virtual ICollection<IncidentBase> IncidentBases { get; set; }
        public virtual ICollection<KbArticleBase> KbArticleBases { get; set; }
        public virtual ICollection<ProductBase> ProductBases { get; set; }
        public virtual TransferHistoryBase TransferHistoryBase { get; set; }
        public virtual ICollection<SubjectBase> SubjectBase1 { get; set; }
        public virtual SubjectBase SubjectBase2 { get; set; }
    }
}
