//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRMOntology.DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class SystemUserBase
    {
        public SystemUserBase()
        {
            this.AccountBases = new HashSet<AccountBase>();
            this.ContactBases = new HashSet<ContactBase>();
            this.TerritoryBases = new HashSet<TerritoryBase>();
            this.SystemUserBase1 = new HashSet<SystemUserBase>();
            this.TeamMemberships = new HashSet<TeamMembership>();
        }
    
        public System.Guid SystemUserId { get; set; }
        public Nullable<System.Guid> TerritoryId { get; set; }
        public System.Guid OrganizationId { get; set; }
        public System.Guid BusinessUnitId { get; set; }
        public Nullable<System.Guid> ParentSystemUserId { get; set; }
        public string FirstName { get; set; }
        public string Salutation { get; set; }
        public string MiddleName { get; set; }
        public string LastName { get; set; }
        public string PersonalEMailAddress { get; set; }
        public string FullName { get; set; }
        public string NickName { get; set; }
        public string Title { get; set; }
        public string InternalEMailAddress { get; set; }
        public string JobTitle { get; set; }
        public string MobileAlertEMail { get; set; }
        public Nullable<int> PreferredEmailCode { get; set; }
        public string HomePhone { get; set; }
        public string MobilePhone { get; set; }
        public Nullable<int> PreferredPhoneCode { get; set; }
        public Nullable<int> PreferredAddressCode { get; set; }
        public string PhotoUrl { get; set; }
        public string DomainName { get; set; }
        public Nullable<int> PassportLo { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<int> PassportHi { get; set; }
        public string DisabledReason { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public Nullable<System.Guid> CreatedBy { get; set; }
        public string EmployeeId { get; set; }
        public Nullable<System.Guid> ModifiedBy { get; set; }
        public Nullable<bool> IsDisabled { get; set; }
        public string GovernmentId { get; set; }
        public byte[] VersionNumber { get; set; }
        public string Skills { get; set; }
        public Nullable<bool> DisplayInServiceViews { get; set; }
        public Nullable<System.Guid> CalendarId { get; set; }
        public Nullable<System.Guid> ActiveDirectoryGuid { get; set; }
        public bool SetupUser { get; set; }
        public Nullable<System.Guid> SiteId { get; set; }
        public string WindowsLiveID { get; set; }
        public int IncomingEmailDeliveryMethod { get; set; }
        public int OutgoingEmailDeliveryMethod { get; set; }
        public Nullable<int> ImportSequenceNumber { get; set; }
        public int AccessMode { get; set; }
        public Nullable<int> InviteStatusCode { get; set; }
        public bool IsActiveDirectoryUser { get; set; }
        public Nullable<System.DateTime> OverriddenCreatedOn { get; set; }
        public Nullable<int> UTCConversionTimeZoneCode { get; set; }
        public Nullable<int> TimeZoneRuleVersionNumber { get; set; }
        public string YomiFullName { get; set; }
        public string YomiLastName { get; set; }
        public string YomiMiddleName { get; set; }
        public string YomiFirstName { get; set; }
        public Nullable<System.Guid> CreatedOnBehalfBy { get; set; }
        public Nullable<decimal> ExchangeRate { get; set; }
        public bool IsIntegrationUser { get; set; }
        public Nullable<System.Guid> ModifiedOnBehalfBy { get; set; }
        public int EmailRouterAccessApproval { get; set; }
        public bool DefaultFiltersPopulated { get; set; }
        public int CALType { get; set; }
        public Nullable<System.Guid> TransactionCurrencyId { get; set; }
        public string YammerEmailAddress { get; set; }
        public bool IsSyncWithDirectory { get; set; }
        public Nullable<System.Guid> ProcessId { get; set; }
        public int UserLicenseType { get; set; }
        public bool IsEmailAddressApprovedByO365Admin { get; set; }
        public string YammerUserId { get; set; }
        public Nullable<System.Guid> EntityImageId { get; set; }
        public bool IsLicensed { get; set; }
        public Nullable<System.Guid> StageId { get; set; }
        public Nullable<System.Guid> TransferHistoryId { get; set; }
    
        public virtual ICollection<AccountBase> AccountBases { get; set; }
        public virtual BusinessUnitBase BusinessUnitBase { get; set; }
        public virtual CalendarBase CalendarBase { get; set; }
        public virtual ICollection<ContactBase> ContactBases { get; set; }
        public virtual SiteBase SiteBase { get; set; }
        public virtual TransferHistoryBase TransferHistoryBase { get; set; }
        public virtual ICollection<TerritoryBase> TerritoryBases { get; set; }
        public virtual TerritoryBase TerritoryBase { get; set; }
        public virtual TransactionCurrencyBase TransactionCurrencyBase { get; set; }
        public virtual ICollection<SystemUserBase> SystemUserBase1 { get; set; }
        public virtual SystemUserBase SystemUserBase2 { get; set; }
        public virtual ICollection<TeamMembership> TeamMemberships { get; set; }
    }
}
