//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRMOntology.DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class TeamMembership
    {
        public System.Guid TeamId { get; set; }
        public System.Guid SystemUserId { get; set; }
        public System.Guid TeamMembershipId { get; set; }
        public byte[] VersionNumber { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public System.DateTime ModifiedOn { get; set; }
        public Nullable<System.Guid> TransferHistoryId { get; set; }
    
        public virtual SystemUserBase SystemUserBase { get; set; }
        public virtual TeamBase TeamBase { get; set; }
        public virtual TransferHistoryBase TransferHistoryBase { get; set; }
    }
}
