//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRMOntology.DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class TeamBase
    {
        public TeamBase()
        {
            this.TeamMemberships = new HashSet<TeamMembership>();
        }
    
        public System.Guid TeamId { get; set; }
        public System.Guid OrganizationId { get; set; }
        public System.Guid BusinessUnitId { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public string EMailAddress { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public Nullable<System.Guid> CreatedBy { get; set; }
        public Nullable<System.Guid> ModifiedBy { get; set; }
        public byte[] VersionNumber { get; set; }
        public Nullable<int> ImportSequenceNumber { get; set; }
        public Nullable<System.DateTime> OverriddenCreatedOn { get; set; }
        public bool IsDefault { get; set; }
        public System.Guid AdministratorId { get; set; }
        public Nullable<System.Guid> QueueId { get; set; }
        public Nullable<decimal> ExchangeRate { get; set; }
        public Nullable<System.Guid> ModifiedOnBehalfBy { get; set; }
        public Nullable<System.Guid> CreatedOnBehalfBy { get; set; }
        public Nullable<System.Guid> TransactionCurrencyId { get; set; }
        public string YomiName { get; set; }
        public Nullable<System.Guid> RegardingObjectId { get; set; }
        public int TeamType { get; set; }
        public Nullable<System.Guid> ProcessId { get; set; }
        public bool SystemManaged { get; set; }
        public Nullable<System.Guid> StageId { get; set; }
        public Nullable<System.Guid> TeamTemplateId { get; set; }
        public Nullable<int> RegardingObjectTypeCode { get; set; }
        public Nullable<System.Guid> TransferHistoryId { get; set; }
    
        public virtual BusinessUnitBase BusinessUnitBase { get; set; }
        public virtual TransferHistoryBase TransferHistoryBase { get; set; }
        public virtual TransactionCurrencyBase TransactionCurrencyBase { get; set; }
        public virtual ICollection<TeamMembership> TeamMemberships { get; set; }
    }
}
