//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRMOntology.DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class TransferHistoryBase
    {
        public TransferHistoryBase()
        {
            this.AccountBases = new HashSet<AccountBase>();
            this.ActivityPartyBases = new HashSet<ActivityPartyBase>();
            this.ActivityPointerBases = new HashSet<ActivityPointerBase>();
            this.AppointmentBases = new HashSet<AppointmentBase>();
            this.BusinessUnitBases = new HashSet<BusinessUnitBase>();
            this.CalendarBases = new HashSet<CalendarBase>();
            this.CampaignActivityBases = new HashSet<CampaignActivityBase>();
            this.CampaignActivityItemBases = new HashSet<CampaignActivityItemBase>();
            this.CampaignBases = new HashSet<CampaignBase>();
            this.CampaignItemBases = new HashSet<CampaignItemBase>();
            this.CampaignResponseBases = new HashSet<CampaignResponseBase>();
            this.CompetitorBases = new HashSet<CompetitorBase>();
            this.CompetitorProducts = new HashSet<CompetitorProduct>();
            this.ConnectionBases = new HashSet<ConnectionBase>();
            this.ConnectionRoleAssociations = new HashSet<ConnectionRoleAssociation>();
            this.ConnectionRoleBases = new HashSet<ConnectionRoleBase>();
            this.ConnectionRoleBaseIds = new HashSet<ConnectionRoleBaseId>();
            this.ContactBases = new HashSet<ContactBase>();
            this.ContractBases = new HashSet<ContractBase>();
            this.ContractDetailBases = new HashSet<ContractDetailBase>();
            this.CustomerAddressBases = new HashSet<CustomerAddressBase>();
            this.EmailBases = new HashSet<EmailBase>();
            this.EntitlementBases = new HashSet<EntitlementBase>();
            this.EquipmentBases = new HashSet<EquipmentBase>();
            this.FaxBases = new HashSet<FaxBase>();
            this.IncidentBases = new HashSet<IncidentBase>();
            this.KbArticleBases = new HashSet<KbArticleBase>();
            this.KbArticleTemplateBases = new HashSet<KbArticleTemplateBase>();
            this.LeadBases = new HashSet<LeadBase>();
            this.LetterBases = new HashSet<LetterBase>();
            this.OpportunityBases = new HashSet<OpportunityBase>();
            this.OrganizationBases = new HashSet<OrganizationBase>();
            this.OwnerBases = new HashSet<OwnerBase>();
            this.PhoneCallBases = new HashSet<PhoneCallBase>();
            this.PriceLevelBases = new HashSet<PriceLevelBase>();
            this.ProductBases = new HashSet<ProductBase>();
            this.ServiceBases = new HashSet<ServiceBase>();
            this.SiteBases = new HashSet<SiteBase>();
            this.SocialProfileBases = new HashSet<SocialProfileBase>();
            this.SubjectBases = new HashSet<SubjectBase>();
            this.SystemUserBases = new HashSet<SystemUserBase>();
            this.TerritoryBases = new HashSet<TerritoryBase>();
            this.TransactionCurrencyBases = new HashSet<TransactionCurrencyBase>();
            this.UoMBases = new HashSet<UoMBase>();
            this.UoMScheduleBases = new HashSet<UoMScheduleBase>();
            this.TeamBases = new HashSet<TeamBase>();
            this.TeamMemberships = new HashSet<TeamMembership>();
            this.AnnotationBases = new HashSet<AnnotationBase>();
            this.TaskBases = new HashSet<TaskBase>();
        }
    
        public System.Guid TransferHistoryId { get; set; }
        public string TransferMapName { get; set; }
        public System.DateTime TransferDate { get; set; }
        public Nullable<System.DateTime> ConvertionDateToOwl { get; set; }
    
        public virtual ICollection<AccountBase> AccountBases { get; set; }
        public virtual ICollection<ActivityPartyBase> ActivityPartyBases { get; set; }
        public virtual ICollection<ActivityPointerBase> ActivityPointerBases { get; set; }
        public virtual ICollection<AppointmentBase> AppointmentBases { get; set; }
        public virtual ICollection<BusinessUnitBase> BusinessUnitBases { get; set; }
        public virtual ICollection<CalendarBase> CalendarBases { get; set; }
        public virtual ICollection<CampaignActivityBase> CampaignActivityBases { get; set; }
        public virtual ICollection<CampaignActivityItemBase> CampaignActivityItemBases { get; set; }
        public virtual ICollection<CampaignBase> CampaignBases { get; set; }
        public virtual ICollection<CampaignItemBase> CampaignItemBases { get; set; }
        public virtual ICollection<CampaignResponseBase> CampaignResponseBases { get; set; }
        public virtual ICollection<CompetitorBase> CompetitorBases { get; set; }
        public virtual ICollection<CompetitorProduct> CompetitorProducts { get; set; }
        public virtual ICollection<ConnectionBase> ConnectionBases { get; set; }
        public virtual ICollection<ConnectionRoleAssociation> ConnectionRoleAssociations { get; set; }
        public virtual ICollection<ConnectionRoleBase> ConnectionRoleBases { get; set; }
        public virtual ICollection<ConnectionRoleBaseId> ConnectionRoleBaseIds { get; set; }
        public virtual ICollection<ContactBase> ContactBases { get; set; }
        public virtual ICollection<ContractBase> ContractBases { get; set; }
        public virtual ICollection<ContractDetailBase> ContractDetailBases { get; set; }
        public virtual ICollection<CustomerAddressBase> CustomerAddressBases { get; set; }
        public virtual ICollection<EmailBase> EmailBases { get; set; }
        public virtual ICollection<EntitlementBase> EntitlementBases { get; set; }
        public virtual ICollection<EquipmentBase> EquipmentBases { get; set; }
        public virtual ICollection<FaxBase> FaxBases { get; set; }
        public virtual ICollection<IncidentBase> IncidentBases { get; set; }
        public virtual ICollection<KbArticleBase> KbArticleBases { get; set; }
        public virtual ICollection<KbArticleTemplateBase> KbArticleTemplateBases { get; set; }
        public virtual ICollection<LeadBase> LeadBases { get; set; }
        public virtual ICollection<LetterBase> LetterBases { get; set; }
        public virtual ICollection<OpportunityBase> OpportunityBases { get; set; }
        public virtual ICollection<OrganizationBase> OrganizationBases { get; set; }
        public virtual ICollection<OwnerBase> OwnerBases { get; set; }
        public virtual ICollection<PhoneCallBase> PhoneCallBases { get; set; }
        public virtual ICollection<PriceLevelBase> PriceLevelBases { get; set; }
        public virtual ICollection<ProductBase> ProductBases { get; set; }
        public virtual ICollection<ServiceBase> ServiceBases { get; set; }
        public virtual ICollection<SiteBase> SiteBases { get; set; }
        public virtual ICollection<SocialProfileBase> SocialProfileBases { get; set; }
        public virtual ICollection<SubjectBase> SubjectBases { get; set; }
        public virtual ICollection<SystemUserBase> SystemUserBases { get; set; }
        public virtual ICollection<TerritoryBase> TerritoryBases { get; set; }
        public virtual ICollection<TransactionCurrencyBase> TransactionCurrencyBases { get; set; }
        public virtual ICollection<UoMBase> UoMBases { get; set; }
        public virtual ICollection<UoMScheduleBase> UoMScheduleBases { get; set; }
        public virtual ICollection<TeamBase> TeamBases { get; set; }
        public virtual ICollection<TeamMembership> TeamMemberships { get; set; }
        public virtual ICollection<AnnotationBase> AnnotationBases { get; set; }
        public virtual ICollection<TaskBase> TaskBases { get; set; }
    }
}
