//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRMOntology.DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class UoMBase
    {
        public UoMBase()
        {
            this.ContractDetailBases = new HashSet<ContractDetailBase>();
            this.ProductBases = new HashSet<ProductBase>();
            this.UoMBase1 = new HashSet<UoMBase>();
        }
    
        public System.Guid UoMId { get; set; }
        public Nullable<System.Guid> BaseUoM { get; set; }
        public string Name { get; set; }
        public System.Guid UoMScheduleId { get; set; }
        public Nullable<decimal> Quantity { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<System.Guid> CreatedBy { get; set; }
        public Nullable<System.Guid> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public Nullable<bool> IsScheduleBaseUoM { get; set; }
        public byte[] VersionNumber { get; set; }
        public Nullable<int> ImportSequenceNumber { get; set; }
        public Nullable<System.DateTime> OverriddenCreatedOn { get; set; }
        public Nullable<System.Guid> ModifiedOnBehalfBy { get; set; }
        public Nullable<System.Guid> CreatedOnBehalfBy { get; set; }
        public Nullable<System.Guid> TransferHistoryId { get; set; }
    
        public virtual ICollection<ContractDetailBase> ContractDetailBases { get; set; }
        public virtual ICollection<ProductBase> ProductBases { get; set; }
        public virtual TransferHistoryBase TransferHistoryBase { get; set; }
        public virtual UoMScheduleBase UoMScheduleBase { get; set; }
        public virtual ICollection<UoMBase> UoMBase1 { get; set; }
        public virtual UoMBase UoMBase2 { get; set; }
    }
}
