//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRMOntology.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CRMOntology.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap BusinessRecommend {
            get {
                object obj = ResourceManager.GetObject("BusinessRecommend", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap BusinessRequired {
            get {
                object obj = ResourceManager.GetObject("BusinessRequired", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;Ontology xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot;
        ///          xsi:schemaLocation=&quot;http://www.comu.edu.tr/eatamuh/ontologies/DatabaseMap DatabaseMap.xsd&quot;&gt;
        ///  &lt;DatabaseMap name=&quot;Template&quot;&gt;
        ///    &lt;Database type=&quot;Source&quot; connectionString=&quot;&quot;/&gt;
        ///    &lt;Database type=&quot;Staging&quot; connectionString=&quot;&quot;/&gt;
        ///    &lt;OWL type=&quot;file&quot; path =&quot;&quot;/&gt;
        ///    &lt;Table name=&quot;TableName&quot;&gt;
        ///      &lt;Map from=&quot;&quot; fromtype=&quot;&quot; to=&quot;&quot; totype=&quot;&quot;/&gt;
        ///    &lt;/Table&gt;
        ///  &lt;/DatabaseMap&gt;
        ///&lt;/Ontology&gt;
        ///.
        /// </summary>
        internal static string DatabaseMapXML {
            get {
                return ResourceManager.GetString("DatabaseMapXML", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;xs:schema attributeFormDefault=&quot;unqualified&quot; elementFormDefault=&quot;qualified&quot; 
        ///           targetNamespace=&quot;http://www.comu.edu.tr/eatamuh/ontologies/DatabaseMap&quot; 
        ///           xmlns:xs=&quot;http://www.w3.org/2001/XMLSchema&quot;&gt;
        ///  &lt;xs:element name=&quot;Ontology&quot;&gt;
        ///  &lt;/xs:element&gt;
        ///  &lt;xs:element name=&quot;DatabaseMap&quot;&gt;
        ///    &lt;xs:complexType&gt;
        ///      &lt;xs:simpleContent&gt;
        ///        &lt;xs:extension base=&quot;xs:string&quot;&gt;
        ///          &lt;xs:attribute type=&quot;xs:string&quot; name=&quot;name&quot; use=&quot;optional&quot;/&gt;
        ///        &lt;/xs:extension&gt;
        ///      &lt;/xs:simpleConte [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string DatabaseMapXSD {
            get {
                return ResourceManager.GetString("DatabaseMapXSD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap DataRow {
            get {
                object obj = ResourceManager.GetObject("DataRow", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap DataTable {
            get {
                object obj = ResourceManager.GetObject("DataTable", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap db_invalid {
            get {
                object obj = ResourceManager.GetObject("db_invalid", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap db_valid {
            get {
                object obj = ResourceManager.GetObject("db_valid", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Loading {
            get {
                object obj = ResourceManager.GetObject("Loading", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap NoConstraint {
            get {
                object obj = ResourceManager.GetObject("NoConstraint", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;Ontology xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot;
        ///          xsi:schemaLocation=&quot;http://www.comu.edu.tr/eatamuh/ontologies/OWLConfiguration OWLConfiguration.xsd&quot;&gt;
        ///  &lt;OWLConfiguration&gt;
        ///    &lt;Database type=&quot;Staging&quot; connectionString=&quot;&quot;/&gt;
        ///    &lt;OWLItem type=&quot;Accurate&quot; low=&quot;-1&quot; medium=&quot;-1&quot; high=&quot;-1&quot; businessrequired=&quot;-1&quot; businessrecommend=&quot;-1&quot; noconstraint=&quot;-1&quot;&gt;
        ///      &lt;Map key=&quot;&quot; value=&quot;&quot;/&gt;
        ///    &lt;/OWLItem&gt;
        ///  &lt;/OWLConfiguration&gt;
        ///&lt;/Ontology&gt;
        ///.
        /// </summary>
        internal static string OWLConfigurationXML {
            get {
                return ResourceManager.GetString("OWLConfigurationXML", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;xs:schema attributeFormDefault=&quot;unqualified&quot; elementFormDefault=&quot;qualified&quot; targetNamespace=&quot;http://www.comu.edu.tr/eatamuh/ontologies/OWLConfiguration&quot; xmlns:xs=&quot;http://www.w3.org/2001/XMLSchema&quot;&gt;
        ///  &lt;xs:element name=&quot;Ontology&quot;&gt;
        ///  &lt;/xs:element&gt;
        ///  &lt;xs:element name=&quot;OWLConfiguration&quot;&gt;
        ///    &lt;xs:complexType&gt;
        ///      &lt;xs:simpleContent&gt;
        ///        &lt;xs:extension base=&quot;xs:string&quot;&gt;      
        ///        &lt;/xs:extension&gt;
        ///      &lt;/xs:simpleContent&gt;
        ///    &lt;/xs:complexType&gt;
        ///  &lt;/xs:element&gt;
        ///  &lt;xs:element name=&quot;Database&quot;&gt;
        ///     [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string OWLConfigurationXSD {
            get {
                return ResourceManager.GetString("OWLConfigurationXSD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap rdf_foldr {
            get {
                object obj = ResourceManager.GetObject("rdf_foldr", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap rdf_icon {
            get {
                object obj = ResourceManager.GetObject("rdf_icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
